export const REGISTRATION = 'REGISTRATION';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


export const GET_MENU_LIST_ITEM = 'GET_MENU_LIST_ITEM';
export const GET_MENU_LIST_ITEM_SUCCESS = 'GET_MENU_LIST_ITEM_SUCCESS';
export const GET_MENU_LIST_ITEM_FAIL = 'GET_MENU_LIST_ITEM_FAIL';


export const SET_PAYMENT = "SET_PAYMENT";
export const SET_PAYMENT_SUCCESS = 'SET_PAYMENT_SUCCESS';
export const SET_CARTLIST = "SET_CARTLIST"
export const SET_ITEM_AMOUNT = "SET_ITEM_AMOUNT"

export const SET_SELECT_VALUE = "SET_SELECT_VALUE";

export const ADD_TO_CART_MENU_ITEM = 'ADD_TO_CART_MENU_ITEM';
export const ADD_TO_CART_MENU_ITEM_SUCCESS = 'ADD_TO_CART_MENU_ITEM_SUCCESS';
export const ADD_TO_CART_MENU_ITEM_FAIL = 'ADD_TO_CART_MENU_ITEM_FAIL';

export const GET_ADD_TO_CART_MENU_ITEM = 'GET_ADD_TO_CART_MENU_ITEM';
export const GET_ADD_TO_CART_MENU_ITEM_SUCCESS = 'GET_ADD_TO_CART_MENU_ITEM_SUCCESS';
export const GET_ADD_TO_CART_MENU_ITEM_FAIL = 'GET_ADD_TO_CART_MENU_ITEM_FAIL';

export const DELETE_ADD_TO_CART_MENU_ITEM = 'DELETE_ADD_TO_CART_MENU_ITEM';
export const DELETE_ADD_TO_CART_MENU_ITEM_SUCCESS = 'DELETE_ADD_TO_CART_MENU_ITEM_SUCCESS';
export const DELETE_ADD_TO_CART_MENU_ITEM_FAIL = 'DELETE_ADD_TO_CART_MENU_ITEM_FAIL';


export const UPDATE_ADD_TO_CART_MENU_ITEM = 'UPDATE_ADD_TO_CART_MENU_ITEM';
export const UPDATE_ADD_TO_CART_MENU_ITEM_SUCCESS = 'UPDATE_ADD_TO_CART_MENU_ITEM_SUCCESS';
export const UPDATE_ADD_TO_CART_MENU_ITEM_FAIL = 'UPDATE_ADD_TO_CART_MENU_ITEM_FAIL';

export const SET_MENU_ID = "SET_MENU_ID";
