export const REGISTRATION = 'REGISTRATION';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


export const GET_MENU_LIST_ITEM = 'GET_MENU_LIST_ITEM';
export const GET_MENU_LIST_ITEM_SUCCESS = 'GET_MENU_LIST_ITEM_SUCCESS';
export const GET_MENU_LIST_ITEM_FAIL = 'GET_MENU_LIST_ITEM_FAIL';


export const SET_PAYMENT = "SET_PAYMENT";
export const SET_PAYMENT_SUCCESS = 'SET_PAYMENT_SUCCESS';
export const SET_CARTLIST = "SET_CARTLIST"
export const SET_ITEM_AMOUNT = "SET_ITEM_AMOUNT"